version: 2

models:
  - name: int_rippling__worker_compensation
    description: "Standardized worker compensation data with historical tracking"
    columns:
      - name: worker_id
        description: "Foreign key to workers table"
        tests:
          - not_null
          - relationships:
              to: ref('base_rippling_workers')
              field: worker_id
      - name: calculated_annual_salary
        description: "Normalized annual salary based on different compensation frequencies"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 364000
      - name: compensation_frequency
        description: "Type of compensation frequency (HOURLY, WEEKLY, MONTHLY, ANNUALLY)"
      - name: is_current_record
        description: "Flag indicating if this is the current compensation record"
      - name: dept_avg_salary
        description: "Average salary within the department"
      - name: company_avg_salary
        description: "Average salary across the company"
      - name: department_id
        data_type: varchar
        tests:
          - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 24
              row_condition: "{{adapter.quote('DEPARTMENT_ID')}} is not null"
      - name: job_title
        data_type: varchar
        tests:
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              min_value: 9
              max_value: 43
              row_condition: "{{adapter.quote('JOB_TITLE')}} is not null"
      - name: payment_type
        data_type: varchar
        tests:
          - accepted_values:
              values:
                - DEFAULT
                - VARIED
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              min_value: 6
              max_value: 7
              row_condition: "{{adapter.quote('PAYMENT_TYPE')}} is not null"
      - name: previous_salary
        data_type: number
        tests:
          - accepted_values:
              values:
                - "0"
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 0
      - name: salary_change_percentage
        data_type: number
        tests:
          - accepted_values:
              values:
                - "0.00"
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 0
      - name: months_since_last_change
        data_type: number
        tests:
          - accepted_values:
              values:
                - "0"
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 0
      - name: department_comp_quartile
        data_type: number
        tests:
          - accepted_values:
              values:
                - "1"
                - "2"
                - "3"
                - "4"
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 4
      - name: is_significant_change
        data_type: boolean
        tests:
          - accepted_values:
              values:
                - "false"
      - name: is_due_for_review
        data_type: boolean
        tests:
          - accepted_values:
              values:
                - "false"
      - name: dbt_loaded_at
        data_type: timestamp_ltz
        tests:
          - accepted_values:
              values:
                - 2025-02-12 14:07:55.787 -0800
      - name: dbt_batch_id
        data_type: varchar
        tests:
          - accepted_values:
              values:
                - 3f1dc5e6-2941-4085-ba77-9b5b7fa85303
          - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 36
              row_condition: "{{adapter.quote('DBT_BATCH_ID')}} is not null"
    tests:
      - dbt_utils.recency:
          field: EFFECTIVE_MONTH
          datepart: day
          interval: 56
      - dbt_utils.recency:
          field: EFFECTIVE_QUARTER
          datepart: day
          interval: 92
      - dbt_utils.recency:
          field: EFFECTIVE_YEAR
          datepart: day
          interval: 366

  - name: int_rippling__worker_leaves
    description: "Processed leave request data with calculated metrics"
    columns:
      - name: leave_request_id
        description: "Unique identifier for the leave request"
        tests:
          - unique
          - not_null
      - name: worker_id
        description: "Foreign key to workers table"
        tests:
          - not_null
          - relationships:
              to: ref('base_rippling_workers')
              field: worker_id
      - name: leave_duration_days
        description: "Duration of leave in days"
      - name: total_leave_days_ytd
        description: "Total leave days taken year to date"
      - name: paid_leave_days_ytd
        description: "Total paid leave days taken year to date"

  - name: int_rippling__worker_time_entries
    description: "Processed time entry data with calculated metrics"
    columns:
      - name: time_entry_id
        description: "Unique identifier for the time entry"
        tests:
          - unique
          - not_null
      - name: worker_id
        description: "Foreign key to workers table"
        tests:
          - relationships:
              to: ref('base_rippling_workers')
              field: worker_id
      - name: regular_hours
        description: "Regular working hours (up to 8 hours per day)"
      - name: overtime_hours
        description: "Overtime hours (beyond 8 hours per day)"
      - name: cumulative_hours_mtd
        description: "Cumulative hours worked month to date"

  - name: int_rippling__department_hierarchy
    description: "Department hierarchy with recursive path calculation"
    columns:
      - name: department_id
        description: "Unique identifier for the department"
        tests:
          - unique
          - not_null
      - name: department_path
        description: "Full hierarchical path of the department"
        tests:
          - not_null
      - name: hierarchy_level
        description: "Level in the department hierarchy (1 being top level)"
      - name: worker_count
        description: "Number of active workers in the department"
      - name: total_compensation
        description: "Total compensation for all workers in the department"
