name: "hr_analytics"
version: "1.0.0"
config-version: 2

profile: "hr_analytics"

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  hr_analytics:
    staging:
      +schema: transformed # Dynamically sets schema based on environment
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: table
    dimensions:
      +schema: analysis
      +materialized: table
    facts:
      +schema: analysis
      +materialized: table
    metrics:
      +schema: analysis
      +materialized: view

