name: "northsight"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "northsight_analytics"

# File path configurations
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  # Variables for different environments
  'dbt_date:time_zone': 'America/Los_Angeles'

# Enable metrics
metrics:
  northsight:
    +enabled: true

models:
  northsight:
    # Config defaults for all models
    +materialized: view
    +schema: analytics
    
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging", "hourly"]
    
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
      +tags: ["intermediate"]
    
    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]
      
      core:
        +schema: core
        +tags: ["core"]
      
      hr:
        +schema: hr
        +tags: ["hr"]
      
      finance:
        +schema: finance
        +tags: ["finance"]

dbt-cloud:
  project-id: 70471823424662
