version: 2

models:
  - name: hr_worker_leave_analysis
    description: "Analyzes leave patterns and trends for workers"
    columns:
      - name: leave_request_id
        description: "Unique identifier for the leave request"
        tests:
          - unique
          - not_null
      - name: total_leave_days_ytd
        description: "Total leave days taken year to date"
      - name: paid_leave_days_ytd
        description: "Total paid leave days taken year to date"
      - name: leave_requests_count_ytd
        description: "Number of leave requests submitted year to date"

  - name: hr_time_attendance_analysis
    description: "Analyzes time and attendance patterns"
    columns:
      - name: time_entry_id
        description: "Unique identifier for the time entry"
        tests:
          - unique
          - not_null
      - name: avg_hours_per_day_mtd
        description: "Average hours worked per day month to date"
      - name: total_overtime_hours_mtd
        description: "Total overtime hours month to date"
      - name: days_worked_mtd
        description: "Number of days worked month to date"

  - name: hr_headcount_analysis
    description: "Analyzes employee headcount trends by department"
    columns:
      - name: department_id
        description: "Unique identifier for the department"
      - name: month_date
        description: "Month of analysis"
      - name: total_headcount
        description: "Total number of employees"
      - name: month_over_month_growth
        description: "Percentage growth in headcount from previous month"

  - name: hr_compensation_analysis
    description: "Analyzes compensation patterns and benchmarks"
    columns:
      - name: dept_avg_salary
        description: "Average salary within department"
      - name: company_avg_salary
        description: "Average salary across company"
      - name: salary_to_dept_avg_ratio
        description: "Individual salary compared to department average"

  - name: hr_turnover_analysis
    description: "Analyzes employee turnover patterns"
    columns:
      - name: turnover_rate
        description: "Monthly turnover rate as a percentage"
      - name: voluntary_terminations
        description: "Number of voluntary terminations"
      - name: avg_tenure_months
        description: "Average tenure of terminated employees in months"

  - name: hr_department_cost_analysis
    description: "Analyzes department-level personnel costs"
    columns:
      - name: monthly_salary_cost
        description: "Total monthly salary cost for department"
      - name: overtime_cost
        description: "Total overtime cost for department"
      - name: total_monthly_cost
        description: "Total monthly personnel cost including benefits"
      - name: month_over_month_cost_change
        description: "Percentage change in total cost from previous month"

  - name: hr_metrics_combined
    description: "Combined HR metrics model for semantic layer"
    columns:
      - name: department_id
        description: "Unique identifier for department"
        tests:
          - not_null
      
      - name: metric_date
        description: "Date the metrics are calculated for"
        tests:
          - not_null
      
      - name: total_headcount
        description: "Total number of employees"
      
      - name: calculated_annual_salary
        description: "Annual salary amount"
      
      - name: turnover_rate
        description: "Employee turnover rate as percentage"
      
      - name: total_monthly_cost
        description: "Total monthly personnel cost" 