version: 2

sources:
  - name: rippling
    description: "Raw Rippling data from Airbyte sync"
    database: PC_FIVETRAN_DB
    schema: AIRBYTE_SCHEMA
    tables:
      - name: workers
        description: "All worker information from Rippling"
        columns:
          - name: id
            description: "Unique identifier for the worker"
            tests:
              - unique
              - not_null
          - name: user_id
            description: "Associated user ID"
          - name: status
            description: "Worker's current status"
            tests:
              - accepted_values:
                  values: ['HIRED', 'ACCEPTED', 'ACTIVE', 'TERMINATED']
      
      - name: compensations
        description: "Worker compensation details"
        columns:
          - name: id
            description: "Unique identifier for compensation record"
            tests:
              - unique
              - not_null

      - name: departments
        description: "Company department information"
        columns:
          - name: id
            description: "Unique identifier for department"
            tests:
              - unique
              - not_null
              
      - name: teams
        description: "Team information"
        columns:
          - name: id
            description: "Unique identifier for team"
            tests:
              - unique
              - not_null

      - name: time_entries
        description: "Time tracking entries"
        columns:
          - name: id
            description: "Unique identifier for time entry"
            tests:
              - unique
              - not_null
          - name: worker_id
            description: "Associated worker ID"
            tests:
              - relationships:
                  to: source('rippling', 'workers')
                  field: id
      - name: leave_requests
        description: "Employee leave requests from Rippling"
        loaded_at_field: "created_at"
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        columns:
          - name: id
            description: "Unique identifier for the leave request"
            tests:
              - unique
              - not_null
          - name: leave_type_id
            description: "ID of the leave type"
            tests:
              - not_null
          - name: status
            description: "Status of the leave request"
            tests:
              - accepted_values:
                  values: ['PENDING', 'APPROVED', 'REJECTED', 'CANCELED']
          - name: start_date
            description: "Start date of the leave"
            tests:
              - not_null
          - name: end_date
            description: "End date of the leave"
            tests:
              - not_null
      
      - name: leave_types
        description: "Types of leave available in the system"
        columns:
          - name: id
            description: "Unique identifier for the leave type"
            tests:
              - unique
              - not_null
          - name: name
            description: "Name of the leave type"
            tests:
              - not_null
          - name: is_paid
            description: "Whether this is a paid leave type"
            tests:
              - not_null