version: 2

sources:
  - name: rippling
    description: "Raw Rippling data from Airbyte sync"
    database: PC_FIVETRAN_DB
    schema: AIRBYTE_SCHEMA
    tables:
      - name: workers
        description: "All worker information from Rippling"
        columns:
          - name: id
            description: "Unique identifier for the worker"
            tests:
              - unique
              - not_null
          - name: user_id
            description: "Associated user ID"
          - name: status
            description: "Worker's current status"
            tests:
              - accepted_values:
                  values: ['HIRED', 'ACCEPTED', 'ACTIVE', 'TERMINATED']
      
      - name: compensations
        description: "Worker compensation details"
        columns:
          - name: id
            description: "Unique identifier for compensation record"
            tests:
              - unique
              - not_null

      - name: departments
        description: "Company department information"
        columns:
          - name: id
            description: "Unique identifier for department"
            tests:
              - unique
              - not_null
              
      - name: teams
        description: "Team information"
        columns:
          - name: id
            description: "Unique identifier for team"
            tests:
              - unique
              - not_null

      - name: time_entries
        description: "Time tracking entries"
        columns:
          - name: id
            description: "Unique identifier for time entry"
            tests:
              - unique
              - not_null
          - name: worker_id
            description: "Associated worker ID"
            tests:
              - relationships:
                  to: source('rippling', 'workers')
                  field: id